name: 'docker image build'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/*.py"
      - "**/*.html"
      - "**/*.css"
      - "**/Dockerfile"
      - "**/requirements.txt"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: ghcr.io/love4taylor/nexttraceweb:latest
